
BuffGuideLocales = {};
BuffGuideLocales["enUS"] = {

	RAID_BUFFS	= "Raid Buffs",
	FOOD_BUFF	= "Food Buff",
	FLASK		= "Flask",
	YES		= "Yes",
	MISSING		= "Missing",

	TIME_S		= "%ss",
	TIME_M		= "%sm",
	TIME_HM		= "%sh %sm",

	BUFF_stats		= "Stats",
	BUFF_stamina		= "Stamina",
	BUFF_attack_power	= "Attack Power",
	BUFF_spell_power	= "Spell Power",
	BUFF_haste		= "Haste",
	BUFF_spell_haste	= "Spell Haste",
	BUFF_crit		= "Critical Strike",
	BUFF_mastery		= "Mastery",

	FROM_DRUID	= "Druid",
	FROM_MONK	= "Monk",
	FROM_PALADIN	= "Paladin",
	FROM_DK		= "DK",
	FROM_HUNTER	= "Hunter",
	FROM_MAGE	= "Mage",
	FROM_SHAMAN	= "Shaman",
	FROM_PRIEST	= "Priest",
	FROM_WARRIOR	= "Warrior",
	FROM_WARLOCK	= "Warlock",
	FROM_ROGUE	= "Rogue",

	FROM_IMP	= "Warlock (Imp)",
	FROM_DK_FU	= "Frost/Unholy DK",
	FROM_SHAM_ENC	= "Enhancement Shaman",
	FROM_SHAM_ELE	= "Elemental Shaman",
	FROM_DRUID_BAL	= "Balance Druid",
	FROM_DRUID_FER	= "Guardian/Feral Druid",
	FROM_SPRIEST	= "Shadow Priest",

	FROM_SHALE	= "BM Hunter (Shale Spider)",
	FROM_SILITHID	= "BM Hunter (Silithid)",
	FROM_WSTRIDER	= "BM Hunter (Waterstrider)",
	FROM_HYENA	= "Hunter (Hyena)",
	FROM_SERPENT	= "Hunter (Serpent)",
	FROM_HYDRA	= "Hunter (Hydra)",
	FROM_WOLF	= "Hunter (Wolf)",
	FROM_DEVILSAUR	= "Hunter (Devilsaur)",
	FROM_QUILEN	= "Hunter (Quilen)",
	FROM_CAT	= "Hunter (Cat)",
	FROM_SPIRIT	= "Hunter (Spirit Beast)",
};
